#!/usr/bin/php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

$app = require __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand();

exit($status);
